version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - ".env.development"
    volumes:
      - ./src:/app/src:ro
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    image: postgres
    restart: always
    env_file:
      - ".env.development"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080