version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ".env.development"
    depends_on:
      - database
  database:
    image: postgres
    env_file:
      - ".env.development"
