CREATE TABLE IF NOT EXISTS user {
    id SERIAL PRIMARY KEY
}

CREATE TABLE IF NOT EXISTS todo {
    id SERIAL PRIMARY KEY,
    
    owner_id INTEGER NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES users(id)
}